name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.platform.name }})
    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: iOS
            sdk: iphoneos

          - name: tvOS
            sdk: appletvos

          - name: macOS
            sdk: macosx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.3"

      - name: Xcode version
        run: xcodebuild -version
        
      - name: Xcode sdks
        run: xcodebuild -showsdks
        
      - name: Show destinations
        run:  xcodebuild  -scheme WelcomeScreen  -showdestinations

      - name: Validate Package.swift
        run: swift package dump-package > /dev/null

      - name: Resolve package dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build Swift Package
        run: |
          xcodebuild \
            -scheme WelcomeScreen \
            -sdk "${{ matrix.platform.sdk }}" \
            -configuration Debug \
            build \
            CODE_SIGNING_ALLOWED=NO